import type { Question } from '../types';

// 顧客向け事前フォーム: 既存のないけんぼーいず公式フォーム項目に準拠
export const customerFormQuestions: Question[] = [
  { id: 'name',            category: '基本情報', question: 'お名前',                                                           kind: 'text',        required: true },
  { id: 'gender',          category: '基本情報', question: '性別',                                                             kind: 'select',      options: ['男性', '女性', 'その他', '未回答'] },
  { id: 'age',             category: '基本情報', question: 'ご年齢',                                                           kind: 'number' },
  { id: 'phone',           category: '基本情報', question: '電話番号',                                                         kind: 'text' },
  { id: 'email',           category: '基本情報', question: 'メールアドレス',                                                   kind: 'text' },
  { id: 'line_name',       category: '基本情報', question: 'LINE表示名',                                                       kind: 'text' },
  { id: 'hearing_method',  category: 'ヒアリング',question: 'ヒアリング方法のご希望',                                          kind: 'select',      options: ['対面', 'オンライン', '電話', 'どちらでも可'] },
  { id: 'area_pref',       category: 'エリア',   question: 'ご検討エリア（都道府県）',                                          kind: 'text' },
  { id: 'station_pref',    category: 'エリア',   question: 'ご検討エリア（路線/最寄駅）',                                       kind: 'text' },
  { id: 'household',       category: 'ご状況',   question: '世帯構成',                                                         kind: 'select',      options: ['単身', '同棲', '夫婦', '家族（お子様あり）', 'その他'] },
  { id: 'consideration',   category: 'ご状況',   question: '購入の検討状況',                                                   kind: 'select',      options: ['すぐにでも購入したい', '半年以内', '1年以内', '将来的に購入したい（時期未定 / 1年以上先）'] },
  { id: 'job',             category: 'ご状況',   question: 'ご職業',                                                           kind: 'select',      options: ['会社員/公務員', '自営業/フリーランス', '経営者/役員', '専業主婦/主夫', 'その他'] },
  { id: 'current_station', category: 'ご状況',   question: '現在お住まいの最寄り駅',                                            kind: 'text' },
  { id: 'workplace_station', category: 'ご状況', question: 'お勤め先の最寄り駅',                                                kind: 'text' },
  { id: 'property_type',   category: '物件',     question: 'ご希望の物件種別',                                                 kind: 'select',      options: ['戸建て', 'マンション', '土地', 'どちらでも可'] },
  { id: 'layout',          category: '物件',     question: 'ご希望の間取り',                                                   kind: 'select',      options: ['1LDK以下', '2LDK', '3LDK', '4LDK以上'] },
  { id: 'age_pref',        category: '物件',     question: 'ご希望の築年数',                                                   kind: 'select',      options: ['新築', '築10年以内', '築20年以内', '未定・こだわりなし'] },
  { id: 'income_band',     category: '資金',     question: '年収（世帯年収）',                                                 kind: 'select',      options: ['400万円台以下', '500-700万円台', '800-1000万円台', '1100-1500万円台', '1500万円以上'] },
  { id: 'budget_band',     category: '資金',     question: 'ご予算',                                                           kind: 'select',      options: ['3000万円台以下', '3000-4000万円台', '4000-5000万円台', '5000-7000万円台', '7000万円以上'] },
  { id: 'consult_topics',  category: '相談',     question: 'ヒアリングで特に相談したいこと（複数可）',                          kind: 'multiselect', options: ['物件選びの考え方', '資金計画/住宅ローン', 'エリアの選定', '購入のタイミング', 'パートナーとの意思決定', '内見の進め方'] },
  { id: 'other_notes',     category: '相談',     question: 'その他お伝えしておきたい事',                                       kind: 'longtext' },
];

// 営業用ヒアリング深掘り質問: 顧客フォームの裏で営業が深掘りする項目
export const salesHearingQuestions: Question[] = [
  {
    id: 'rapport_open',
    category: 'ラポール',
    question: '今日はお時間いただきありがとうございます。本題の前に、最近お休みの日はどんな風に過ごされてますか?',
    hint: '緊張をほぐすアイスブレイク。回答内容から趣味嗜好を把握し、後で物件提案の文脈に活かす。',
    kind: 'longtext',
  },
  {
    id: 'why_buy',
    category: '購入動機',
    question: 'まずざっくりで構いません。なぜマイホーム購入を考え始めましたか?きっかけがあれば教えてください。',
    hint: '★最重要。動機が明確なら温度感が高い。「なんとなく」なら時期未定の理由をさらに深掘り。',
    kind: 'longtext',
    required: true,
  },
  {
    id: 'timing_detail',
    category: '購入時期',
    question: '「将来的に・1年以上先」と回答いただいてますが、具体的にイメージされている時期はありますか?(例: 来年春、結婚後、転職後、貯蓄が貯まったら 等)',
    hint: '時期未定客のホット度判別の核心。条件待ちの場合、その条件が満たされるとすぐ買う可能性ありなので具体化が重要。',
    kind: 'longtext',
    required: true,
  },
  {
    id: 'partner_role',
    category: 'パートナー',
    question: 'パートナー様も購入のご検討に参加されてますか?ご結婚やお子様のご予定はありますか?',
    hint: '同棲の場合、意思決定者がもう1人いる。次回はパートナー同席を提案。家族計画は間取り選定に影響。',
    kind: 'longtext',
    required: true,
  },
  {
    id: 'income_breakdown',
    category: '資金計画',
    question: '世帯年収の内訳を教えていただけますか?（ご本人・パートナー様それぞれおおよそで）',
    hint: 'ペアローン or 単独ローンの選択肢に直結。雇用形態（正社員/契約/フリー）も合わせて聞く。',
    kind: 'longtext',
  },
  {
    id: 'budget_definition',
    category: '資金計画',
    question: 'ご予算「4000万円台」は物件価格ですか?それとも諸費用も含めた総予算ですか?',
    hint: '★聞かないと後で食い違う重大ポイント。諸費用は物件価格の7-10%。',
    kind: 'select',
    options: ['物件価格のみ', '諸費用込みの総予算', '未定/相談したい'],
    required: true,
  },
  {
    id: 'down_payment',
    category: '資金計画',
    question: '頭金として準備可能な金額はおおよそどのぐらいですか?',
    hint: '頭金 + 諸費用で500-800万以上が望ましい。少額なら諸費用ローンの提案も視野。',
    kind: 'longtext',
  },
  {
    id: 'pre_screening',
    category: '資金計画',
    question: '住宅ローンの事前審査はもうお受けになりましたか?',
    hint: '済んでいない場合、提携金融機関の事前審査を次回アクションに。',
    kind: 'select',
    options: ['受けて承認済み', '申込中', 'まだ受けていない', '受ける予定なし'],
  },
  {
    id: 'why_saginuma',
    category: 'エリア',
    question: 'なぜ「鷺沼」をご希望ですか?（職場アクセス・相場・雰囲気・縁故 など）',
    hint: '理由次第で代替エリア提案の余地がわかる。「なんとなく」なら宮前平・たまプラーザ・あざみ野も候補に。',
    kind: 'longtext',
    required: true,
  },
  {
    id: 'walk_distance',
    category: 'エリア',
    question: '駅徒歩何分以内をご希望ですか?',
    hint: '徒歩条件次第で予算内に収まる物件範囲が大きく変わる。鷺沼は坂が多いので徒歩動線確認も必須。',
    kind: 'select',
    options: ['5分以内', '10分以内', '15分以内', '20分以内', 'こだわらない'],
  },
  {
    id: 'why_house',
    category: '物件条件',
    question: '戸建てに決めた理由を教えてください。マンションは選択肢にありませんか?',
    hint: '予算4000万円台 × 鷺沼で戸建てだと中古中心になる。マンションも視野なら選択肢が広がる。',
    kind: 'longtext',
  },
  {
    id: 'must_haves',
    category: '物件条件',
    question: '駐車場・庭・階数・木造/鉄骨など、譲れない条件はありますか?',
    hint: 'MUST と WANT を分けて聞く。MUSTが多すぎると予算内で見つからない可能性を予め示唆。',
    kind: 'longtext',
  },
  {
    id: 'new_or_used',
    category: '物件条件',
    question: '新築と中古、どちらに気持ちが傾いていますか?',
    hint: '鷺沼予算4000万円台なら中古（築15-30年）が現実的。リフォーム前提なら予算配分の話に。',
    kind: 'select',
    options: ['新築一択', '新築希望だが中古も', 'どちらでも', '中古希望', '未定'],
  },
  {
    id: 'competition',
    category: '競合状況',
    question: '他の不動産会社さんやポータルサイトでも情報収集されていますか?',
    hint: '競合の名前が出たら、その会社との差別化ポイントを意識した提案に切り替える。',
    kind: 'longtext',
  },
  {
    id: 'experience',
    category: '情報収集',
    question: 'これまで内見や物件見学をされたご経験はありますか?',
    hint: '経験ありなら「なぜ買わなかったか」を聞くと選定軸が見える。未経験なら鷺沼で1件提案して反応を見る。',
    kind: 'longtext',
  },
  {
    id: 'concerns',
    category: '懸念',
    question: '今、購入に向けて不安や懸念に思っていることは何ですか?',
    hint: '★ヒアリング後半に必ず聞く。ここで挙がった不安に直接対応する次回提案を組む。',
    kind: 'longtext',
    required: true,
  },
  {
    id: 'next_action',
    category: 'クロージング',
    question: '本日のお話を踏まえ、次のアクションとして「物件情報の定期送付・事前審査・内見」のうち、どれが今のお気持ちに近いですか?',
    hint: '3択クロージング。決められない場合は「では物件情報の送付から」と最も小さなYESを取りに行く。',
    kind: 'select',
    options: ['物件情報の定期送付', '事前審査を受けたい', '内見を希望', 'まだどれも決められない'],
    required: true,
  },
];
